name: teknodef
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.0.5
  sqflite: ^2.0.2
  path: ^1.7.0
  webview_flutter: ^3.0.0
  google_fonts: ^2.3.0
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.13
  expandable_bottom_bar: ^2.0.2
  expandable: ^5.0.1
  intl: ^0.17.0
  flutter_staggered_grid_view: ^0.4.0-nullsafety.3

dev_dependencies:
    flutter_test:
      sdk: flutter


    flutter_lints: ^1.0.0
    flutter_launcher_icons: ^0.9.2
flutter_native_splash:
  android: true
  ios: true
  background_image: images/ark.png
  image: images/a.png


flutter:

  uses-material-design: true

  assets:
    #  - assets/sorular.json
      - images/ark.png
      - images/a.png
      - images/dijidef.png
  #fonts:
   # - family: Sans
    #  fonts:
     #   - asset: assets/fonts/ProductSans-Regular.ttf
      #  - asset: assets/fonts/ProductSans-Italic.ttf
       #   style: italic
        #- asset: assets/fonts/ProductSans-Bold.ttf
         # weight: 700
  